export const projects = [
  { title: "ABAYA BY IQRA", category: "web-design", thumb: "./My projects/web/ABAYA BY IQRA/abaya by iqra.webp", media: "./My projects/web/ABAYA BY IQRA/abaya by iqra.webp" },
  { title: "ALGHANI TRAVELERS", category: "web-design", thumb: "./My projects/web/ALGHANI TRAVELERS/alghani travelers.webp", media: "./My projects/web/ALGHANI TRAVELERS/alghani travelers.webp" },
  { title: "BLOOMRICH", category: "web-design", thumb: "./My projects/web/BLOOMRICH/BLOOMRICH.webp", media: "./My projects/web/BLOOMRICH/BLOOMRICH.webp" },
  { title: "CARDTOPIA", category: "web-design", thumb: "./My projects/web/CARDTOPIA/cardtopia.webp", media: "./My projects/web/CARDTOPIA/cardtopia.webp" },
  { title: "COLLIDE", category: "web-design", thumb: "./My projects/web/Collide/collide.webp", media: "./My projects/web/Collide/collide.webp" },
  { title: "FASHIONISTA", category: "web-design", thumb: "./My projects/web/FASHIONISTA/fashion.jpg", media: "./My projects/web/FASHIONISTA/landing page.jpg" },
  { title: "IC WEBSITE", category: "web-design", thumb: "./My projects/web/IC WEBSITE/ic website.webp", media: "./My projects/web/IC WEBSITE/ic website.webp" },
  { title: "IFIX", category: "web-design", thumb: "./My projects/web/IFIX/ifix final.webp", media: "./My projects/web/IFIX/ifix final.webp" },
  { title: "IRIANA REAL ESTATE", category: "web-design", thumb: "./My projects/web/IRIANA REAL ESTATE/Irina Homepage-2.webp", media: "./My projects/web/IRIANA REAL ESTATE/Irina Homepage-2.webp" },
  { title: "ISTUDENTLY", category: "web-design", thumb: "./My projects/web/ISTUDENTLY DASHBOARD AND WEBSITE/istudent.ly.png", media: "./My projects/web/ISTUDENTLY DASHBOARD AND WEBSITE/istudently arabic.webp" },
  { title: "LOGICAL LINKS", category: "web-design", thumb: "./My projects/web/LOGICAL LINKS/logical links.webp", media: "./My projects/web/LOGICAL LINKS/logical links.webp" },
  { title: "MIO MONDO", category: "web-design", thumb: "./My projects/web/MIO MONDO/mio mondo.webp", media: "./My projects/web/MIO MONDO/mio modo.webp" },
  { title: "MOTON NOIR", category: "web-design", thumb: "./My projects/web/MOTON NOIR/moton noir.webp", media: "./My projects/web/MOTON NOIR/moton noir.webp" },
  { title: "NABSTER", category: "web-design", thumb: "./My projects/web/NABSTER/Nabster.webp", media: "./My projects/web/NABSTER/WEB NABSTER.webp" },
  { title: "NATIONWIDE EQUITY", category: "web-design", thumb: "./My projects/web/NATIONWIDE EQUITY/Nation equity.webp", media: "./My projects/web/NATIONWIDE EQUITY/Nationwide Equity.webp" },
  { title: "OCTO MEDIA", category: "web-design", thumb: "./My projects/web/OCTO MEDIA/octo media.webp", media: "./My projects/web/OCTO MEDIA/octo media.webp" },
  { title: "PARK PRO", category: "web-design", thumb: "./My projects/web/PARK PRO/park pro new.webp", media: "./My projects/web/PARK PRO/park pro new.webp" },
  { title: "PARKEASE", category: "web-design", thumb: "./My projects/web/PARKEASE/parkease.webp", media: "./My projects/web/PARKEASE/parkease.webp" },
  { title: "PROM DRESS", category: "web-design", thumb: "./My projects/web/PROM DRESS/PROM DRESS.webp", media: "./My projects/web/PROM DRESS/PROM DRESS.webp" },
  { title: "RAPID REPLACE", category: "web-design", thumb: "./My projects/web/RAPID REPLACE/rapid replace.webp", media: "./My projects/web/RAPID REPLACE/rapid replace.webp" },
  { title: "REHMANI SPORTS", category: "web-design", thumb: "./My projects/web/REHMANI SPORTS/rehmani sports.webp", media: "./My projects/web/REHMANI SPORTS/rehmani sports.webp" },
  { title: "ROBOSPHERE", category: "web-design", thumb: "./My projects/web/ROBOSPHERE/aura 21.webp", media: "./My projects/web/ROBOSPHERE/aura 21.webp" },
  { title: "SAUDI VISA SERVICE", category: "web-design", thumb: "./My projects/web/SAUDI VISA SERVICE/saudi visa service.webp", media: "./My projects/web/SAUDI VISA SERVICE/saudi visa service.webp" },
  { title: "SKORA", category: "web-design", thumb: "./My projects/web/SKORA/final skora design.webp", media: "./My projects/web/SKORA/final skora design.webp" },
  { title: "SWIFT VISA JOURNEY", category: "web-design", thumb: "./My projects/web/SWIFT VISA JOURNEY/swi.webp", media: "./My projects/web/SWIFT VISA JOURNEY/swi.webp" },
  { title: "TRINITY SCHOOL", category: "web-design", thumb: "./My projects/web/TRINITY SCHOOL/trinity blue.webp", media: "./My projects/web/TRINITY SCHOOL/trinity blue.webp" },
  { title: "TRIPNEST", category: "web-design", thumb: "./My projects/web/TRIPNEST/tripnest.webp", media: "./My projects/web/TRIPNEST/tripnest hero.webp" },



  { title: "CHARITY APP", category: "app-design", thumb: "./My projects/app/charity/THUMBNAIL.jpg", media: "./My projects/app/charity/1.png" },
  { title: "COFFEE APP", category: "app-design", thumb: "./My projects/app/coffee/THUMNAIL.png", media: "./My projects/app/coffee/1.png" },
  { title: "FOODIE CORE", category: "app-design", thumb: "./My projects/app/foodie core/THUMBNAIL.png", media: "./My projects/app/foodie core/1.png" },
  { title: "IMAGE TO EXCEL", category: "app-design", thumb: "./My projects/app/image to excel/THUMBNAIL.png", media: "./My projects/app/image to excel/1.png" },
  { title: "YOGA APP", category: "app-design", thumb: "./My projects/app/yoga/THUMBNAIL.png", media: "./My projects/app/yoga/THUMBNAIL.png" },
  { title: "GRAPHIC 1", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (1).png", media: "./My projects/Graphic/1 (1).png" },
  { title: "GRAPHIC 2", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (2).png", media: "./My projects/Graphic/1 (2).png" },
  { title: "GRAPHIC 3", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (3).png", media: "./My projects/Graphic/1 (10).png" },
  { title: "GRAPHIC 4", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (4).png", media: "./My projects/Graphic/1 (3).png" },
  { title: "GRAPHIC 5", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (5).png", media: "./My projects/Graphic/1 (11).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/THUMBNAIL  (6).png", media: "./My projects/Graphic/1 (9).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (4).png", media: "./My projects/Graphic/1 (4).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (5).png", media: "./My projects/Graphic/1 (5).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (6).png", media: "./My projects/Graphic/1 (6).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (7).png", media: "./My projects/Graphic/1 (7).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (8).png", media: "./My projects/Graphic/1 (8).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (12).png", media: "./My projects/Graphic/1 (12).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (13).png", media: "./My projects/Graphic/1 (13).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (14).png", media: "./My projects/Graphic/1 (14).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (15).png", media: "./My projects/Graphic/1 (15).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (16).png", media: "./My projects/Graphic/1 (16).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (17).png", media: "./My projects/Graphic/1 (17).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (18).png", media: "./My projects/Graphic/1 (18).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (19).png", media: "./My projects/Graphic/1 (19).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (20).png", media: "./My projects/Graphic/1 (20).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (21).png", media: "./My projects/Graphic/1 (21).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (22).png", media: "./My projects/Graphic/1 (22).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (23).png", media: "./My projects/Graphic/1 (23).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (24).png", media: "./My projects/Graphic/1 (24).png" },
  { title: "GRAPHIC 6", category: "graphic-design", thumb: "./My projects/Graphic/1 (25).png", media: "./My projects/Graphic/1 (25).png" },
  { title: "LOGO 1", category: "logo-design", thumb: "./My projects/logo/logo (1).png", media: "./My projects/logo/logo (1).jpeg" },
  { title: "LOGO 2", category: "logo-design", thumb: "./My projects/logo/logo (2).png", media: "./My projects/logo/logo (2).jpeg" },
  { title: "LOGO 3", category: "logo-design", thumb: "./My projects/logo/logo (3).png", media: "./My projects/logo/logo (3).png" },
  { title: "LOGO 4", category: "logo-design", thumb: "./My projects/logo/logo (4).png", media: "./My projects/logo/logo (4).png" },
  // { title: "VIDEO 1", category: "video", thumb: "./My projects/vedio/V (1).mp4", media: "./My projects/vedio/V (1).mp4" },
  // { title: "VIDEO 2", category: "video", thumb: "./My projects/vedio/V (2).mp4", media: "./My projects/vedio/V (2).mp4" },
  // { title: "VIDEO 3", category: "video", thumb: "./My projects/vedio/V (3).mp4", media: "./My projects/vedio/V (3).mp4" },
  // { title: "VIDEO 4", category: "video", thumb: "./My projects/vedio/V (4).mp4", media: "./My projects/vedio/V (4).mp4" },
  // { title: "VIDEO 5", category: "video", thumb: "./My projects/vedio/V (5).mp4", media: "./My projects/vedio/V (5).mp4" },
  // { title: "VIDEO 6", category: "video", thumb: "./My projects/vedio/V (6).mp4", media: "./My projects/vedio/V (6).mp4" },
  // { title: "VIDEO 7", category: "video", thumb: "./My projects/vedio/V (7).mp4", media: "./My projects/vedio/V (7).mp4" },
  // { title: "VIDEO 8", category: "video", thumb: "./My projects/vedio/V (8).mp4", media: "./My projects/vedio/V (8).mp4" },
  // { title: "VIDEO 9", category: "video", thumb: "./My projects/vedio/V (9).mp4", media: "./My projects/vedio/V (9).mp4" }
];
